services:
  postgres:
    image: postgres:latest
    container_name: fasoshop
    environment:
      POSTGRES_USER: opensource
      POSTGRES_PASSWORD: sourceopen
      POSTGRES_DB: fasoshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
