name: Build Image for Render & Publish Docker Images

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    name: Build and Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose -f render.docker-compose.yml build

      - name: web-server-build-full
        run: |
          # Tag the web service image built by docker-compose
          docker tag quick-start-full:latest ${{ secrets.DOCKERHUB_USERNAME }}/quick-start-full:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/quick-start-full:latest
